### ISSUE TITLE
About pose_bounds.npy file format

### ISSUE THREAD

**Issue by SunshineWYC** [luchongshan/OMMO#1]
Many Thanks for your great work,there is no doubt that this dataset will build a meaningful benchmark for this domain. Some things are confused about "pose_bounds.npy" file which contains an array which shape is [N_views, 17]. Issues are listed hoping for your reply:
1. how can I convert the 17-dim vector to camera params (extrinsic and intrinsic) ?
2. what's the camera coordinate system definition (maybe x right, y down, z forward)?
3. Could you please supplement more info about camera extrinsic ? (camera-to-world or world-to-camera)

Hoping for your reply.

**Comment by luchongshan** [comment]
Thank you for your interest in our dataset! ommo uses the camera pose format of the mainstream nerf dataset. Please refer to the following conversion files for details：
https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py
https://github.com/lioryariv/volsdf/blob/main/DATA_CONVENTION.md
And some explanations for camera files in the dataset：
[https://colmap.github.io/format.html](url)
I hope this can solve your doubts.
